### ISSUE TITLE
LSP Specification Tracking Issue

### ISSUE THREAD

**Issue by mpickering** [mpickering/ghcide#23]
This is a tracking issue to verify that we support all the recent LSP features and to think about whether any of the unused features could provide a better experience. For each item in the list we should understand what it means in terms of the specification and then comment about whether we can use it or not. 

# 3.16.0 (xx/xx/xxxx)
- [ ]  Add semantic token support
- [ ]  Add call hierarchy support (#18)
- [ ]  Add support for insert and replace ranges on CompletionItem
- [ ]  Add support for diagnsotic codes
- [ ] Add support for tags on SymbolInformation and DocumentSymbol
# 3.15.0 (01/14/2020)
- [ ] Add generic progress reporting support.
- [ ] Add specific work done progress reporting support to requests where applicable.
- [ ] Add specific partial result progress support to requests where applicable.
- [ ] Add support for textDocument/selectionRange.
- [ ] Add support for server and client information.
- [ ] Add signature help context.
- [ ] Add version on PublishDiagnosticsParams
- [ ] Add CodeAction#isPreferred support.
- [ ] Add CompletionItem#tag support.
- [ ] Add Diagnostic#tag support.
- [ ] Add DocumentLink#tooltip support.
- [ ] Add trimTrailingWhitespace, insertFinalNewline and trimFinalNewlines to FormattingOptions.
- [ ] Clarified WorkspaceSymbolParams#query parameter.
# 3.14.0 (12/13/2018)
- [ ] Add support for signature label offsets.
- [ ] Add support for location links.
- [ ] Add support for textDocument/declaration request.
# 3.13.0 (9/11/2018)
- [ ] Add support for file and folder operations (create, rename, move) to workspace edits.
# 3.12.0 (8/23/2018)
- [ ] Add support for textDocument/prepareRename request.
# 3.11.0 (8/21/2018)
- [ ] Add support for CodeActionOptions to allow a server to provide a list of code action it supports.
# 3.10.0 (7/23/2018)
- [ ] Add support for hierarchical document symbols as a valid response to a textDocument/documentSymbol request.
- [ ] Add support for folding ranges as a valid response to a textDocument/foldingRange request.
# 3.9.0 (7/10/2018)
- [ ] Add support for preselect property in CompletionItem
# 3.8.0 (6/11/2018)
- [x] Added support for CodeAction literals to the textDocument/codeAction request.
- [ ] ColorServerCapabilities.colorProvider can also be a boolean
- [ ] Corrected ColorPresentationParams.colorInfo to color (as in the d.ts and in implementations)
# 3.7.0 (4/5/2018)
- [x] Added support for related information to Diagnostics.

**Comment by jneira** [comment]
There is a similar one in lsp-haskell: https://github.com/alanz/haskell-lsp/issues/134
Afaiu ghcide/hls would need that haskell-lsp supports them
